### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by FirionHope** [ahzaidi/VXTwitter#1]
I've tried on two browsers, Brave with a bunch of extensions, and a fresh install of chrome. When I copy the links and go to paste them they just show up as x.com. Tried both control + C and also clicking the copy link button, and right clicking the url and clicking copy, none seem to actually work. Am I doing something wrong?

**Comment by ahzaidi** [comment]
I assume you're on Mac correct? I will roll out a fix for this

**Comment by FirionHope** [comment]
Sorry, I should've specified. I'm on Windows 10, on what I assume is a fairly recent build.

**Comment by ahzaidi** [comment]
So, when you click on a blank section of a page/tweet. You press Control + C and nothing happens?

**Comment by FirionHope** [comment]
It turns out I was misunderstanding that does work! Thank you. You might want to change the description on the page slightly, as it was written I didn't quite understand I needed to do that. But ty, great extension, I'll leave a good review.

**Comment by ahzaidi** [comment]
I will modify the description. Thank you for the info!
